name: Generate Snake Animation

on:
  schedule:
    - cron: "0 12 * * *"
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: naluisaelias  
          outputs: |
            snake-animation.svg?palette=github-dark&color_snake=fe428e&color_dots=#a9fef7,#f8d847,#141321,#fe428e,#f8d847
            snake-animation.gif?color_snake=fe428e&color_dots=#a9fef7,#f8d847,#141321,#fe428e,#f8d847
          
      - name: Push Snake Animation to README
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          target_branch: output
          build_dir: dist
